### ISSUE TITLE
Is it work now?

### ISSUE THREAD

**Issue by stoixxxman** [lkazberova/pronunciation-finder#7]

**Comment by lkazberova** [comment]
@stoixxxman something wrong with `cambridge` dictionary, but you can try with `oxford`
```bash
pronunciation-finder car --dictionary oxford --play
```

**Comment by stoixxxman** [comment]
Thank you very much! I don't know this comand. I hope developer to solve this problem soon.

**Comment by stoixxxman** [comment]
And help me do the same just from text file .txt:
"pronunciation-finder (1.txt) --dictionary oxford" - this line is wrong...

**Comment by lkazberova** [comment]
Please try with `pronunciation-finder $(cat 1.txt) --dictionary oxford --play`
