### ISSUE TITLE
i can not install it

### ISSUE THREAD

**Issue by caokhai1331999** [lkazberova/pronunciation-finder#9]
![Untitled](https://user-images.githubusercontent.com/58471517/77839144-71709400-71a4-11ea-961e-d6f40021eeee.png)
is that error for my npm or for the app i am so confused

**Comment by lkazberova** [comment]
Hi @caokhai1331999,
 I suppose it's outdated sure, but in your logs I see that you don't have required library "You need to install the latest version of Visual Studio"
